apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otus-sample-order.fullname" . }}
data:
  QUARKUS_DATASOURCE_JDBC_URL: {{ .Values.os.db.url }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.os.kafka.url }}

