{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "otus-sample-ing2.fullname" . }}
  labels:
    {{- include "otus-sample-ing2.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /auth
            backend:
              serviceName: my-auth-otus-sample-auth
              servicePort: 8000
          - path: /swagger-ui
            backend:
              serviceName: my-auth-otus-sample-auth
              servicePort: 8000
          - path: /openapi
            backend:
              serviceName: my-auth-otus-sample-auth
              servicePort: 8000
