apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otus-sample-email.fullname" . }}
type: Opaque
data:
  USERNAME: {{ .Values.os.db.username | b64enc }}
  PASSWORD: {{ .Values.os.db.password | b64enc }}
